[package]
name = "compute-certificate"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
faer = "0.24.0"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1"
